### ISSUE TITLE
feat - Geocode API

### ISSUE THREAD

**Issue by Seongbuming** [pay-map/Paymap-Server#1]
# Geocode API
장소의 주소를 통해 좌표를 요청하는 API입니다.

## URI
`GET` /geocode

## Request Fields
|Field|Type|Description|
|---|---|---|
|key|String|요청 검증을 위한 키|
|address|String|주소(ex.서울시 군자동  능동로 209)|
|coordinate|String|결과가 복수일 시 거리에 따라 우선순위를 부여하기 위한 좌표|

## Response Fields
|Field|Type|Description|
|---|---|---|
|branchAddress|String|지번주소|
|roadAddress|String|도로명주소|
|x|Number|좌표X(경도)|
|y|Number|좌표Y(위도)|

**Comment by AzelyFox** [comment]
added in e9d3d2cdb32b8bbd91dd3cc029f4ea6e4fe50c72
